### ISSUE TITLE
"Warn" log setting misfunctioning

### ISSUE THREAD

**Issue by Erallie** [czottmann/obsidian-log-to-note#14]
The "warn" log setting is printing **all** messages. I found what to fix:

In `utils.ts` in lines 91 and 92,
replace this:
```
    case "warn":
      return !["debug","info","log"].includes(logLevel);
```
with this:
```
    case "warn":
      return !["debug","info","log"].includes(logEvent.level);
```
like in lines 93 and 94 below it.

**Comment by czottmann** [comment]
Thanks for the report, I'll see that I'll release a fixed version later today!

**Comment by czottmann** [comment]
Fixed, thank you! Deployed in https://github.com/czottmann/obsidian-logstravaganza/releases/tag/2.1.1
