### ISSUE TITLE
[ZCO-229] Make target note configurable

### ISSUE THREAD

**Issue by czottmann** [czottmann/obsidian-log-to-note#2]
Right now, all log output is saved to `LOGGING-NOTE.md`. Make it configurable via a Settings view.

<sub>[ZCO-229](https://linear.app/actionsdotwork/issue/ZCO-229/make-target-note-configurable)</sub>

**Comment by claremacrae** [comment]
Where people share the same settings across multiple devices, via Obsidian Sync, they will get conflicts if there is a single setting for target not name.

#7 provides a related idea. Perhaps the machine name could be used as a placeholder inside the 'target note name' user setting somehow...

**Comment by czottmann** [comment]
I'm not 100% sure yet how to proceed re settings (needs more thinking through) but I do like #7. Automatically using the device name as default might be a good strategy. It'd work fine in sync'd vaults OOTB but once settings are implemented the user could fine-tune it if necessary.

**Comment by alangrainger** [comment]
In my opinion, specifying a folder name would be the best option. The current names for the log notes are perfect - I just want to put them somewhere other than the root.

**Comment by czottmann** [comment]
@alangrainger, @claremacrae The output path is now configurable, and there's also the option to tag the output filename with the current date.

Just out as part of v2.0.0!
