### ISSUE TITLE
Get plugin listed in the Community Plugin index

### ISSUE THREAD

**Issue by czottmann** [czottmann/obsidian-log-to-note#5]

**Comment by czottmann** [comment]
Submitted: [Add plugin Logstravaganza by czottmann · Pull Request #2008 · obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases/pull/2008)

**Comment by claremacrae** [comment]
Hooray - congratulations on getting this done. 🎉

**Comment by alangrainger** [comment]
I didn't want to open an issue just for this comment, but wanted to say Thank you!! This is a godsend for mobile debugging, what a brilliant idea 🔥

**Comment by czottmann** [comment]
Thanks, @alangrainger!
