### ISSUE TITLE
line-break missing

### ISSUE THREAD

**Issue by gapmiss** [czottmann/obsidian-log-to-note#6]
Z,

Noticed that the log tables were missing line-breaks. This change did the trick.

In `logging.ts` change line # 81:

```js
const linesToAppend = newLines.join("\n");
```

to:

```js
const linesToAppend = newLines.join("\n")+"\n";
```

Handy little plugin.

**Comment by claremacrae** [comment]
Here is an example of some output as a result of this issue...

Scroll right to see the end of the last line....

```
| 2023-07-23T09:13:09.141Z |  | log | Line numbers are on |
| 2023-07-23T09:13:09.141Z |  | log | Readable line length is off |
| 2023-07-23T09:13:09.216Z |  | log | loading plugin: Obsidian Charts |
| 2023-07-23T09:13:11.247Z | Calendar | debug | Trying to switch Moment.js global locale to en-gb, got en-gb |
| 2023-07-23T09:13:11.406Z |  | error | {} || 2023-07-23T09:13:17.393Z |  | log | Dataview: all 5436 files have been indexed in 5.982s (5435 cached, 0 skipped). || 2023-07-23T09:13:20.601Z |  | log | Dataview: Dropped cache entries for 5 deleted files. 
```

I looked because I was trying to work out why I wasn't seeing the `Dataview: Dropped cache entries for 5 deleted files.` message in my log, in Reading view.

**Comment by czottmann** [comment]
Thanks, @gapmiss! Sorry, somehow this ticket flew under my radar. Issue will be fixed in the upcoming version, due next week!

**Comment by czottmann** [comment]
Added in 1.2.0, just released. Thanks, you two! 🙏🏼
