### ISSUE TITLE
Include machine name in default target note name

### ISSUE THREAD

**Issue by claremacrae** [czottmann/obsidian-log-to-note#7]
Huge thanks for this plugin. It is really going to help with user support on the Tasks plugin.

This is a slightly more simpler alternative to  #2, as it does not require adding any settings code and UI.

### Scenario

I have a vault which is synced via Obsidian Sync across 3 devices.

If I have the plugin enabled on more than one of these devices, then there will be constant contention and sync conflicts between devices in the content of `LOGGING-NOTE.md`.

### Suggested solution

Please could you consider appending the name of the device to the default filename automatically, so that users get non-conflicting behaviour out of the box.

**Comment by czottmann** [comment]
Hi @claremacrae, thanks, that's an excellent suggestion!

Also, your thanks make me unreasonably happy. I'm a big fan of your work and now I am able to give something back, which feels really nice. 🙌🏼

**Comment by claremacrae** [comment]
Wow - thank you for the kind words!

**Comment by czottmann** [comment]
@claremacrae Do you happen to know how to get the device name on mobile? On desktop, it's straightforward (`os.hostname()`) but since I can't use the Node.js API on mobile …

**Comment by claremacrae** [comment]
I’m on mobile at the moment so can’t check. Sorry. 

I think if you console.log  `app` you might find something. 

Otherwise, I might search in #plugin-dev on Discord. And then ask there. 

When using Obsidian Sync, the log shows machine name in a particular format, I think. And I feel it would be good to try to use that same value, if possible.

**Comment by czottmann** [comment]
Good suggestion, thanks! After some serious digging around in Discord, I came across [this post](https://discord.com/channels/686053708261228577/840286264964022302/947728074294845453):

`app.internalPlugins.plugins["sync"].instance.getDefaultDeviceName()`

Looks like it fits the bill!

**Comment by claremacrae** [comment]
OK. What happens if Sync is disabled? Worth testing with that, I feel.

**Comment by claremacrae** [comment]
This is all really interesting. 

There is also a [nearby post](https://discord.com/channels/686053708261228577/840286264964022302/947728426968698880):

See above message for way to grab the Device Name that Sync is using (whether system default or specified by the user) from the Sync plugin internals 🙂

```js
let syncPlugin = app.internalPlugins.plugins["sync"].instance;
console.log(syncPlugin.deviceName ? syncPlugin.deviceName : syncPlugin.getDefaultDeviceName());
```

**Comment by czottmann** [comment]
In my case, Sync *is* disabled but Sync is in by default because it's a core plugin and all that. I'm certain `.getDefaultDeviceName()` will do the trick but over the next few days I'll poke around its source code some more.

**Comment by claremacrae** [comment]
> In my case, Sync _is_ disabled but Sync is in by default because it's a core plugin and all that. I'm certain `.getDefaultDeviceName()` will do the trick but over the next few days I'll poke around its source code some more.

OK great. It's not obvious from the Sync docs but it's possible for users to rename their machine for sync:

![4BD58C55-D0BE-42EF-AD1A-21996A981B2F](https://github.com/czottmann/obsidian-logstravaganza/assets/4840096/7f512f6b-7857-4659-a81c-c67a8b19f2c8)

I think that code snippet I posted above would help you, if you wanted to use the user's own name, if supplied...

**Comment by czottmann** [comment]
Oh, now I see, I misread your post, then. Yes, that's true, it should adhere to the user's preference.

**Comment by czottmann** [comment]
Added in 1.2.0, just released. (Found some time and energy, it was a slow Sunday.)

**Comment by claremacrae** [comment]
It works great. Thank you!
