### ISSUE TITLE
Logging Note is a Zombie

### ISSUE THREAD

**Issue by conreid-838** [czottmann/obsidian-log-to-note#8]
Uninstalling this plug-in leaves files behind that continue to force a logging note to be created repeatedly.

**Comment by czottmann** [comment]
Thanks for the report, @conreid-838. I'll look into it!

**Comment by czottmann** [comment]
@conreid-838 I have a hard time reproducing the issue. Could you give me more details? On which platform does this happen? Do you use iCloud Sync?

**Comment by czottmann** [comment]
Can't reproduce, no feedback from reporter in 2 months. Closing.
